server:
    port: 8081
    servlet:
        context-path: /creditcard/api/

spring:
    datasource:
        url: jdbc:sqlserver://localhost;databaseName=BankCreditCard 
        username: sa
        password: makeitso
    jpa:
        show-sql: true
        properties:
             hibernate:
                 dialect: org.hibernate.dialect.SQLServer2012Dialect
                 format_sql: true

schedular:
    cron:
        expression:
             tenMinutes: 40 * * * * ?


rewards:
    businessGold:
          groceries: 0.5
          fuel: 2.0
          travel: 5.5
          shopping: 3.1
          other: 0.2
    moneyback:
          groceries: 1.5
          fuel: 2.0
          travel: 1.7
          shopping: 1.3
          other: 0.1
    platinumTimes:
          groceries: 2.0
          fuel: 2.3
          travel: 3.7
          shopping: 2.5
          other: 0.2
    worldMaster:
          groceries: 3.0
          fuel: 3.5
          travel: 5.0
          shopping: 2.7
          other: 0.3

springdoc:
    swagger-ui:
          path: "/swagger-ui.html"